chore/#14 : yml 파일 수정

diff --git a/.github/workflows/android_ci.yml b/.github/workflows/android_ci.yml
--- a/.github/workflows/android_ci.yml
+++ b/.github/workflows/android_ci.yml
@@ -41,6 +41,10 @@ jobs:
       - name: Touch local properties
         run: touch local.properties
 
+      - name: Debug Base64 Decoding
+        run: |
+          echo "$FIREBASE_SECRET" | base64 --decode || echo "Base64 Decode Failed"
+
       # ✅ google-services.json 복원 (base64 디코딩)
       - name: Decode google-services.json
         env:
